/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: BatteryData_.idl
  Source: BatteryData_.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_BATTERYDATA__HPP
#define DDSCXX_BATTERYDATA__HPP

#include <cstdint>
#include <string>

namespace pnd_adam
{
namespace msg
{
namespace dds_
{
class BatteryData_
{
private:
 int64_t timestamp_ms_ = 0;
 float voltage_ = 0.0f;
 float current_ = 0.0f;
 float power_ = 0.0f;
 float wh_accumulated_ = 0.0f;
 std::string status_;

public:
  BatteryData_() = default;

  explicit BatteryData_(
    int64_t timestamp_ms,
    float voltage,
    float current,
    float power,
    float wh_accumulated,
    const std::string& status) :
    timestamp_ms_(timestamp_ms),
    voltage_(voltage),
    current_(current),
    power_(power),
    wh_accumulated_(wh_accumulated),
    status_(status) { }

  int64_t timestamp_ms() const { return this->timestamp_ms_; }
  int64_t& timestamp_ms() { return this->timestamp_ms_; }
  void timestamp_ms(int64_t _val_) { this->timestamp_ms_ = _val_; }
  float voltage() const { return this->voltage_; }
  float& voltage() { return this->voltage_; }
  void voltage(float _val_) { this->voltage_ = _val_; }
  float current() const { return this->current_; }
  float& current() { return this->current_; }
  void current(float _val_) { this->current_ = _val_; }
  float power() const { return this->power_; }
  float& power() { return this->power_; }
  void power(float _val_) { this->power_ = _val_; }
  float wh_accumulated() const { return this->wh_accumulated_; }
  float& wh_accumulated() { return this->wh_accumulated_; }
  void wh_accumulated(float _val_) { this->wh_accumulated_ = _val_; }
  const std::string& status() const { return this->status_; }
  std::string& status() { return this->status_; }
  void status(const std::string& _val_) { this->status_ = _val_; }
  void status(std::string&& _val_) { this->status_ = _val_; }

  bool operator==(const BatteryData_& _other) const
  {
    (void) _other;
    return timestamp_ms_ == _other.timestamp_ms_ &&
      voltage_ == _other.voltage_ &&
      current_ == _other.current_ &&
      power_ == _other.power_ &&
      wh_accumulated_ == _other.wh_accumulated_ &&
      status_ == _other.status_;
  }

  bool operator!=(const BatteryData_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::pnd_adam::msg::dds_::BatteryData_>::getTypeName()
{
  return "pnd_adam::msg::dds_::BatteryData_";
}

template <> constexpr bool TopicTraits<::pnd_adam::msg::dds_::BatteryData_>::isSelfContained()
{
  return false;
}

template <> constexpr bool TopicTraits<::pnd_adam::msg::dds_::BatteryData_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::pnd_adam::msg::dds_::BatteryData_>::type_map_blob_sz() { return 446; }
template<> constexpr unsigned int TopicTraits<::pnd_adam::msg::dds_::BatteryData_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::pnd_adam::msg::dds_::BatteryData_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x8c,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xa4,  0x3a,  0x1d,  0x52,  0xe9,  0x36,  0x39, 
 0x6d,  0x0d,  0x09,  0xf9,  0x6e,  0xaf,  0xf0,  0x00,  0x74,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x64,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x05,  0x73,  0xf4,  0x70,  0xb7,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0xe4,  0x37,  0xba,  0x43,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x43,  0xb5,  0xc9,  0x17,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x62,  0xcd,  0x27,  0x59,  0x00, 
 0x0b,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x15,  0x21,  0xe5,  0x25,  0x00, 
 0x0c,  0x00,  0x00,  0x00,  0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x9a,  0xcb,  0x44,  0x54, 
 0x01,  0x01,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0xc0,  0x97,  0x4a,  0x6d,  0x35,  0x3b,  0x31, 
 0x4b,  0x7e,  0xc7,  0x1b,  0xf6,  0x38,  0x0d,  0x00,  0xe9,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00, 
 0x2a,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x70,  0x6e,  0x64,  0x5f, 
 0x61,  0x64,  0x61,  0x6d,  0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a, 
 0x3a,  0x42,  0x61,  0x74,  0x74,  0x65,  0x72,  0x79,  0x44,  0x61,  0x74,  0x61,  0x5f,  0x00,  0x00,  0x00, 
 0xb1,  0x00,  0x00,  0x00,  0x06,  0x00,  0x00,  0x00,  0x1b,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x05,  0x00,  0x0d,  0x00,  0x00,  0x00,  0x74,  0x69,  0x6d,  0x65,  0x73,  0x74,  0x61,  0x6d, 
 0x70,  0x5f,  0x6d,  0x73,  0x00,  0x00,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x08,  0x00,  0x00,  0x00,  0x76,  0x6f,  0x6c,  0x74,  0x61,  0x67,  0x65,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00, 
 0x08,  0x00,  0x00,  0x00,  0x63,  0x75,  0x72,  0x72,  0x65,  0x6e,  0x74,  0x00,  0x00,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0x03,  0x00,  0x00,  0x00,  0x01,  0x00,  0x09,  0x00,  0x06,  0x00,  0x00,  0x00, 
 0x70,  0x6f,  0x77,  0x65,  0x72,  0x00,  0x00,  0x00,  0x1d,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x09,  0x00,  0x0f,  0x00,  0x00,  0x00,  0x77,  0x68,  0x5f,  0x61,  0x63,  0x63,  0x75,  0x6d, 
 0x75,  0x6c,  0x61,  0x74,  0x65,  0x64,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x15,  0x00,  0x00,  0x00, 
 0x05,  0x00,  0x00,  0x00,  0x01,  0x00,  0x70,  0x00,  0x07,  0x00,  0x00,  0x00,  0x73,  0x74,  0x61,  0x74, 
 0x75,  0x73,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0xf2,  0xc0,  0x97,  0x4a,  0x6d,  0x35,  0x3b,  0x31,  0x4b,  0x7e,  0xc7,  0x1b,  0xf6,  0x38,  0x0d,  0xf1, 
 0xa4,  0x3a,  0x1d,  0x52,  0xe9,  0x36,  0x39,  0x6d,  0x0d,  0x09,  0xf9,  0x6e,  0xaf,  0xf0, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::pnd_adam::msg::dds_::BatteryData_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xa4,  0x3a,  0x1d,  0x52,  0xe9,  0x36,  0x39,  0x6d,  0x0d,  0x09,  0xf9, 
 0x6e,  0xaf,  0xf0,  0x00,  0x78,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0xc0,  0x97,  0x4a,  0x6d,  0x35,  0x3b,  0x31,  0x4b,  0x7e,  0xc7,  0x1b, 
 0xf6,  0x38,  0x0d,  0x00,  0xed,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::pnd_adam::msg::dds_::BatteryData_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::pnd_adam::msg::dds_::BatteryData_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::pnd_adam::msg::dds_::BatteryData_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::pnd_adam::msg::dds_::BatteryData_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::pnd_adam::msg::dds_::BatteryData_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.timestamp_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.voltage()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.current()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.power()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.wh_accumulated()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!write_string(streamer, instance.status(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::pnd_adam::msg::dds_::BatteryData_& instance, bool as_key) {
  auto &props = get_type_props<::pnd_adam::msg::dds_::BatteryData_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::pnd_adam::msg::dds_::BatteryData_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.timestamp_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.voltage()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.current()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.power()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.wh_accumulated()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!read_string(streamer, instance.status(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::pnd_adam::msg::dds_::BatteryData_& instance, bool as_key) {
  auto &props = get_type_props<::pnd_adam::msg::dds_::BatteryData_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::pnd_adam::msg::dds_::BatteryData_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.timestamp_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.voltage()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.current()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.power()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.wh_accumulated()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!move_string(streamer, instance.status(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::pnd_adam::msg::dds_::BatteryData_& instance, bool as_key) {
  auto &props = get_type_props<::pnd_adam::msg::dds_::BatteryData_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::pnd_adam::msg::dds_::BatteryData_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.timestamp_ms()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.voltage()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 2:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.current()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 3:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.power()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 4:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.wh_accumulated()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 5:
      if (!streamer.start_member(*prop))
        return false;
      if (!max_string(streamer, instance.status(), 0))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::pnd_adam::msg::dds_::BatteryData_& instance, bool as_key) {
  auto &props = get_type_props<::pnd_adam::msg::dds_::BatteryData_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_BATTERYDATA__HPP
