/****************************************************************

  Generated by Eclipse Cyclone DDS IDL to CXX Translator
  File name: HandState_.idl
  Source: HandState_.hpp
  Cyclone DDS: v0.10.2

*****************************************************************/
#ifndef DDSCXX_HANDSTATE__HPP
#define DDSCXX_HANDSTATE__HPP

#include <cstdint>
#include <array>

namespace pnd_adam
{
namespace msg
{
namespace dds_
{
class HandState_
{
private:
 std::array<uint32_t, 12> position_ = { };
 uint32_t reserve_ = 0;

public:
  HandState_() = default;

  explicit HandState_(
    const std::array<uint32_t, 12>& position,
    uint32_t reserve) :
    position_(position),
    reserve_(reserve) { }

  const std::array<uint32_t, 12>& position() const { return this->position_; }
  std::array<uint32_t, 12>& position() { return this->position_; }
  void position(const std::array<uint32_t, 12>& _val_) { this->position_ = _val_; }
  void position(std::array<uint32_t, 12>&& _val_) { this->position_ = _val_; }
  uint32_t reserve() const { return this->reserve_; }
  uint32_t& reserve() { return this->reserve_; }
  void reserve(uint32_t _val_) { this->reserve_ = _val_; }

  bool operator==(const HandState_& _other) const
  {
    (void) _other;
    return position_ == _other.position_ &&
      reserve_ == _other.reserve_;
  }

  bool operator!=(const HandState_& _other) const
  {
    return !(*this == _other);
  }

};

}

}

}

#include "dds/topic/TopicTraits.hpp"
#include "org/eclipse/cyclonedds/topic/datatopic.hpp"

namespace org {
namespace eclipse {
namespace cyclonedds {
namespace topic {

template <> constexpr const char* TopicTraits<::pnd_adam::msg::dds_::HandState_>::getTypeName()
{
  return "pnd_adam::msg::dds_::HandState_";
}

template <> constexpr bool TopicTraits<::pnd_adam::msg::dds_::HandState_>::isKeyless()
{
  return true;
}

#ifdef DDSCXX_HAS_TYPE_DISCOVERY
template<> constexpr unsigned int TopicTraits<::pnd_adam::msg::dds_::HandState_>::type_map_blob_sz() { return 282; }
template<> constexpr unsigned int TopicTraits<::pnd_adam::msg::dds_::HandState_>::type_info_blob_sz() { return 100; }
template<> inline const uint8_t * TopicTraits<::pnd_adam::msg::dds_::HandState_>::type_map_blob() {
  static const uint8_t blob[] = {
 0x57,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf1,  0xfe,  0x48,  0xf7,  0xd1,  0xe3,  0x65,  0x22, 
 0x42,  0x2f,  0xd1,  0xf2,  0x35,  0xd8,  0xa6,  0x00,  0x3f,  0x00,  0x00,  0x00,  0xf1,  0x51,  0x01,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x2f,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x16,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x0c,  0x07,  0x47,  0x57,  0xfe,  0x07,  0x00,  0x00,  0x0b,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x01,  0x00,  0x07,  0x9c,  0x3b,  0x62,  0x94,  0x00,  0x92,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0xf2,  0x98,  0x21,  0x78,  0x36,  0xc4,  0x68,  0x44,  0x65,  0x9e,  0x22,  0x84, 
 0xa3,  0x47,  0x86,  0x00,  0x7a,  0x00,  0x00,  0x00,  0xf2,  0x51,  0x01,  0x00,  0x28,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x20,  0x00,  0x00,  0x00,  0x70,  0x6e,  0x64,  0x5f,  0x61,  0x64,  0x61,  0x6d, 
 0x3a,  0x3a,  0x6d,  0x73,  0x67,  0x3a,  0x3a,  0x64,  0x64,  0x73,  0x5f,  0x3a,  0x3a,  0x48,  0x61,  0x6e, 
 0x64,  0x53,  0x74,  0x61,  0x74,  0x65,  0x5f,  0x00,  0x46,  0x00,  0x00,  0x00,  0x02,  0x00,  0x00,  0x00, 
 0x23,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x01,  0x00,  0x90,  0xf3,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x00,  0x00,  0x0c,  0x07,  0x00,  0x00,  0x09,  0x00,  0x00,  0x00,  0x70,  0x6f,  0x73,  0x69, 
 0x74,  0x69,  0x6f,  0x6e,  0x00,  0x00,  0x00,  0x00,  0x16,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00, 
 0x01,  0x00,  0x07,  0x00,  0x08,  0x00,  0x00,  0x00,  0x72,  0x65,  0x73,  0x65,  0x72,  0x76,  0x65,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x22,  0x00,  0x00,  0x00,  0x01,  0x00,  0x00,  0x00,  0xf2,  0x98,  0x21,  0x78, 
 0x36,  0xc4,  0x68,  0x44,  0x65,  0x9e,  0x22,  0x84,  0xa3,  0x47,  0x86,  0xf1,  0xfe,  0x48,  0xf7,  0xd1, 
 0xe3,  0x65,  0x22,  0x42,  0x2f,  0xd1,  0xf2,  0x35,  0xd8,  0xa6, };
  return blob;
}
template<> inline const uint8_t * TopicTraits<::pnd_adam::msg::dds_::HandState_>::type_info_blob() {
  static const uint8_t blob[] = {
 0x60,  0x00,  0x00,  0x00,  0x01,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf1,  0xfe,  0x48,  0xf7,  0xd1,  0xe3,  0x65,  0x22,  0x42,  0x2f,  0xd1,  0xf2, 
 0x35,  0xd8,  0xa6,  0x00,  0x43,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00,  0x02,  0x10,  0x00,  0x40,  0x28,  0x00,  0x00,  0x00,  0x24,  0x00,  0x00,  0x00, 
 0x14,  0x00,  0x00,  0x00,  0xf2,  0x98,  0x21,  0x78,  0x36,  0xc4,  0x68,  0x44,  0x65,  0x9e,  0x22,  0x84, 
 0xa3,  0x47,  0x86,  0x00,  0x7e,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x00,  0x04,  0x00,  0x00,  0x00, 
 0x00,  0x00,  0x00,  0x00, };
  return blob;
}
#endif //DDSCXX_HAS_TYPE_DISCOVERY

} //namespace topic
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

namespace dds {
namespace topic {

template <>
struct topic_type_name<::pnd_adam::msg::dds_::HandState_>
{
    static std::string value()
    {
      return org::eclipse::cyclonedds::topic::TopicTraits<::pnd_adam::msg::dds_::HandState_>::getTypeName();
    }
};

}
}

REGISTER_TOPIC_TYPE(::pnd_adam::msg::dds_::HandState_)

namespace org{
namespace eclipse{
namespace cyclonedds{
namespace core{
namespace cdr{

template<>
propvec &get_type_props<::pnd_adam::msg::dds_::HandState_>();

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool write(T& streamer, const ::pnd_adam::msg::dds_::HandState_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!write(streamer, instance.position()[0], instance.position().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!write(streamer, instance.reserve()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool write(S& str, const ::pnd_adam::msg::dds_::HandState_& instance, bool as_key) {
  auto &props = get_type_props<::pnd_adam::msg::dds_::HandState_>();
  str.set_mode(cdr_stream::stream_mode::write, as_key);
  return write(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool read(T& streamer, ::pnd_adam::msg::dds_::HandState_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!read(streamer, instance.position()[0], instance.position().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!read(streamer, instance.reserve()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool read(S& str, ::pnd_adam::msg::dds_::HandState_& instance, bool as_key) {
  auto &props = get_type_props<::pnd_adam::msg::dds_::HandState_>();
  str.set_mode(cdr_stream::stream_mode::read, as_key);
  return read(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool move(T& streamer, const ::pnd_adam::msg::dds_::HandState_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!move(streamer, instance.position()[0], instance.position().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!move(streamer, instance.reserve()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::pnd_adam::msg::dds_::HandState_& instance, bool as_key) {
  auto &props = get_type_props<::pnd_adam::msg::dds_::HandState_>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props.data()); 
}

template<typename T, std::enable_if_t<std::is_base_of<cdr_stream, T>::value, bool> = true >
bool max(T& streamer, const ::pnd_adam::msg::dds_::HandState_& instance, entity_properties_t *props) {
  (void)instance;
  if (!streamer.start_struct(*props))
    return false;
  auto prop = streamer.first_entity(props);
  while (prop) {
    switch (prop->m_id) {
      case 0:
      if (!streamer.start_member(*prop))
        return false;
      if (!streamer.start_consecutive(true, true))
        return false;
      if (!max(streamer, instance.position()[0], instance.position().size()))
        return false;
      if (!streamer.finish_consecutive())
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
      case 1:
      if (!streamer.start_member(*prop))
        return false;
      if (!max(streamer, instance.reserve()))
        return false;
      if (!streamer.finish_member(*prop))
        return false;
      break;
    }
    prop = streamer.next_entity(prop);
  }
  return streamer.finish_struct(*props);
}

template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool max(S& str, const ::pnd_adam::msg::dds_::HandState_& instance, bool as_key) {
  auto &props = get_type_props<::pnd_adam::msg::dds_::HandState_>();
  str.set_mode(cdr_stream::stream_mode::max, as_key);
  return max(str, instance, props.data()); 
}

} //namespace cdr
} //namespace core
} //namespace cyclonedds
} //namespace eclipse
} //namespace org

#endif // DDSCXX_HANDSTATE__HPP
